import {afterEach,describe,expect,it,vi} from 'vitest';
import {JSDOM} from 'jsdom';
import {DisplayHimotoki} from '../ext/js/display/display-himotoki.js';
const entry={type:'term',headwords:[{index:0,term:'猫',reading:'ねこ',sources:[{deinflectedText:'猫'}]}],definitions:[{dictionary:'Jitendex',sequences:[1467640],entries:['cat']}],pronunciations:[]};
function pending(){let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};}
function setup(enable=true){const dom=new JSDOM('<div class="entry"><div class="actions"></div></div>',{url:'https://example.test/read'});vi.stubGlobal('window',dom.window);vi.stubGlobal('document',dom.window.document);const api={himotokiGetStatus:vi.fn(async()=>({signedIn:true})),himotokiGetSaved:vi.fn(async()=>({favoriteKeys:[]})),himotokiAddFavorite:vi.fn(async()=>({added:true}))};const actions=new Map(),listeners=new Map();const display={application:{api},dictionaryEntries:[entry],dictionaryEntryNodes:[document.querySelector('.entry')],selectedIndex:0,history:{state:{sentence:{text:'猫が好き',offset:0},url:'https://example.test/read',documentTitle:'Test'}},query:'猫',fullQuery:'猫が好き',queryOffset:0,hotkeyHandler:{registerActions:xs=>xs.forEach(([k,v])=>actions.set(k,v))},on:(k,v)=>listeners.set(k,v),displayGenerator:{instantiateTemplate:()=>{const b=document.createElement('button');b.className='action-button';b.dataset.action='save-himotoki';return b;}},createNotification:()=>({setContent(){},open(){},close(){}})};const h=new DisplayHimotoki(display);h.prepare();listeners.get('optionsUpdated')({options:{himotoki:{enable,includeSentence:true,includeUrl:true,folderId:''}}});listeners.get('contentUpdateStart')();listeners.get('contentUpdateComplete')();return {h,api,hotkey:actions.get('addHimotokiNote'),button:()=>document.querySelector('button')};}
afterEach(()=>vi.unstubAllGlobals());
describe('audit: actual popup controller',()=>{
 it('the registered save hotkey opens quick-add with integration disabled',()=>{const s=setup(false);const open=vi.spyOn(window,'open').mockImplementation(()=>null);expect(s.button()).toBeNull();s.hotkey();expect(open).toHaveBeenCalledTimes(1);expect(open.mock.calls[0][0]).toContain('/save?text=');console.log('Disabled integration hotkey opens:',open.mock.calls[0][0]);});
 it('two hotkeys submit two writes despite the disabled saving button',async()=>{const s=setup();await vi.waitFor(()=>expect(s.h._signedIn).toBe(true));const p=pending();s.api.himotokiAddFavorite.mockReturnValue(p.promise);s.hotkey();expect(s.button().disabled).toBe(true);s.hotkey();expect(s.api.himotokiAddFavorite).toHaveBeenCalledTimes(2);console.log('Pending save request count:',s.api.himotokiAddFavorite.mock.calls.length);p.resolve({added:true});});
 it('background saved-state refresh re-enables a pending save button',async()=>{const s=setup();await vi.waitFor(()=>expect(s.h._signedIn).toBe(true));const p=pending();s.api.himotokiAddFavorite.mockReturnValue(p.promise);s.hotkey();expect(s.button().disabled).toBe(true);await s.h._updateSavedState();expect(s.button().disabled).toBe(false);expect(s.button().dataset.himotokiState).toBe('ready');console.log('Pending button after saved-state refresh:',s.button().dataset.himotokiState);p.resolve({added:true});});
});
